
# Generated by Django 5.2.6 on 2025-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
