
# Generated by Django 5.2.6 on 2025-09-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_keyword_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='department',
            field=models.CharField(choices=[('civil_engineering', 'Civil Engineering'), ('mechanical_engineering', 'Mechanical Engineering'), ('eee', 'Electrical & Electronics Engineering (EEE)'), ('ece', 'Electronics & Communication (ECE)'), ('cse_it', 'Computer Science & IT'), ('chemical_engineering', 'Chemical Engineering'), ('aerospace_engineering', 'Aerospace Engineering'), ('biomedical_engineering', 'Biomedical Engineering'), ('industrial_engineering', 'Industrial Engineering'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('mathematics_statistics', 'Mathematics / Statistics'), ('botany', 'Botany'), ('zoology', 'Zoology'), ('biotechnology_microbiology', 'Biotechnology / Microbiology'), ('environmental_science_ecology', 'Environmental Science / Ecology'), ('geology_geography', 'Geology / Geography'), ('mbbs', 'MBBS'), ('bds', 'BDS'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('physiotherapy', 'Physiotherapy'), ('public_health', 'Public Health'), ('history', 'History'), ('political_science', 'Political Science'), ('sociology_social_work', 'Sociology / Social Work'), ('psychology', 'Psychology'), ('philosophy_ethics', 'Philosophy / Ethics'), ('languages', 'Languages'), ('fine_arts_performing_arts', 'Fine Arts / Performing Arts'), ('commerce_accounting', 'Commerce / Accounting'), ('business_admin_management', 'Business Admin / Management'), ('llb_llm', 'LLB / LLM'), ('education', 'Education'), ('library_information_science', 'Library & Information Science'), ('hotel_management', 'Hotel Management'), ('agriculture_horticulture_forestry', 'Agriculture / Horticulture / Forestry'), ('veterinary', 'Veterinary'), ('economy', 'Economy')], max_length=50),
        ),
    ]
