
# Generated by Django 5.2.6 on 2025-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_interviewquestion_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('botany', 'Botany'), ('zoology', 'Zoology'), ('Physics', 'Physics'), ('Maths', 'Maths'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Political science', 'Political science'), ('Science', 'Science'), ('Tamil', 'Tamil'), ('English', 'English')], max_length=30),
        ),
    ]
