
# Generated by Django 5.2.6 on 2025-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_formula_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='subject',
            field=models.CharField(choices=[('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Biology(Botany)', 'Biology(Botany)'), ('Biology(Zoology)', 'Biology(Zoology)'), ('Physics', 'Physics'), ('Maths', 'Maths'), ('Economics', 'Economics'), ('History', 'History'), ('Geography', 'Geography'), ('Political science', 'Political science'), ('Science', 'Science'), ('Tamil', 'Tamil'), ('English', 'English')], max_length=30),
        ),
    ]
