
# Generated by Django 5.2.6 on 2025-09-22 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_formula_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquiz',
            name='quiz_date',
            field=models.DateField(default=datetime.date(2025, 9, 23), help_text='The date this question is assigned to the daily quiz'),
            preserve_default=False,
        ),
    ]
