
# Generated by Django 5.2.6 on 2025-09-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dailyquiz_quiz_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquizattempt',
            options={'ordering': ['-last_attempt_date']},
        ),
        migrations.RenameField(
            model_name='dailyquizattempt',
            old_name='last_attempt',
            new_name='last_attempt_date',
        ),
    ]
