
# Generated by Django 5.2.6 on 2025-09-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dailyquizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquizattempt',
            options={'ordering': ['-quiz_date']},
        ),
        migrations.RenameField(
            model_name='dailyquizattempt',
            old_name='last_attempt_date',
            new_name='quiz_date',
        ),
        migrations.AlterField(
            model_name='dailyquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dailyquizattempt',
            unique_together={('user', 'quiz_date')},
        ),
    ]
