
# Generated by Django 5.2.6 on 2025-09-27 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dailyquizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyquiz',
            options={'ordering': ['quiz_date', 'id'], 'verbose_name': 'Daily Quiz Question', 'verbose_name_plural': 'Daily Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='dailyquizattempt',
            options={'ordering': ['-quiz_date', '-attempted_at'], 'verbose_name': 'Daily Quiz Attempt', 'verbose_name_plural': 'Daily Quiz Attempts'},
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyquiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyquizattempt',
            name='answers',
            field=models.JSONField(default=list, help_text="List of user's answers in order ['A', 'B', 'C', ...]"),
        ),
        migrations.AddField(
            model_name='dailyquizattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='correct_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', help_text='Select the correct option (A, B, C or D).', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_a',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_c',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='option_d',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailyquiz',
            name='quiz_date',
            field=models.DateField(db_index=True, help_text='The date this question is assigned to the daily quiz'),
        ),
        migrations.AlterField(
            model_name='dailyquizattempt',
            name='percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyquizattempt',
            name='quiz_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyquizattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
